// categories.data.js

export const CATEGORIES = [
  {
    id: 1,
    nom: "Musique",
    emoji: "",
    stats: "12 chaînes · 48 émissions",
    meta: "Pop, Jazz, Afrobeat, Hip-Hop, Classique...",
    couleur: "text-purple-600",
    bg: "bg-purple-50",
    bordure: "border-purple-400",
    chaines: [
      { nom: "Radio Afrobeat", initials: "RA", couleur: "bg-purple-500", auditeurs: "12 400", top: true },
      { nom: "Jazz FM", initials: "JF", couleur: "bg-indigo-500", auditeurs: "8 200", top: false },
      { nom: "Hip-Hop Nation", initials: "HN", couleur: "bg-pink-500", auditeurs: "15 600", top: true },
    ],
    emissions: [
      { nom: "Afrobeat Mix", info: "Chaque vendredi 20h — DJ Kofi", live: true },
      { nom: "Jazz du Soir", info: "Lun-Ven 22h — Miles & Friends", live: false },
      { nom: "Top Hip-Hop", info: "Samedi 18h — Classement hebdo", live: false },
      { nom: "Découvertes Pop", info: "Dimanche 16h — Nouveautés", live: false },
      { nom: "Classique Lounge", info: "Mer 21h — Orchestre symphonique", live: false },
      { nom: "Reggae Vibes", info: "Jeudi 19h — Roots & Culture", live: true },
    ],
  },
  {
    id: 2,
    nom: "Sport",
    emoji: "",
    stats: "8 chaînes · 36 émissions",
    meta: "Football, Basketball, Athlétisme, Tennis...",
    couleur: "text-green-600",
    bg: "bg-green-50",
    bordure: "border-green-400",
    chaines: [
      { nom: "Sport 24", initials: "S2", couleur: "bg-green-500", auditeurs: "22 000", top: true },
      { nom: "Foot Radio", initials: "FR", couleur: "bg-emerald-500", auditeurs: "18 500", top: true },
      { nom: "Basket Live", initials: "BL", couleur: "bg-teal-500", auditeurs: "9 300", top: false },
    ],
    emissions: [
      { nom: "Match du Jour", info: "Tous les soirs 20h — Résultats en direct", live: true },
      { nom: "Analyse Foot", info: "Lundi 19h — Revue de la journée", live: false },
      { nom: "NBA Nuit", info: "Mar & Jeu 2h — Matchs NBA en direct", live: true },
      { nom: "Athlétisme Plus", info: "Samedi 10h — Compétitions mondiales", live: false },
      { nom: "Tennis Talk", info: "Dimanche 14h — Tournois & interviews", live: false },
      { nom: "Sport Business", info: "Vendredi 18h — Coulisses du sport", live: false },
    ],
  },
  {
    id: 3,
    nom: "Environnement",
    emoji: "",
    stats: "5 chaînes · 24 émissions",
    meta: "Climat, Nature, Écologie, Développement durable...",
    couleur: "text-lime-600",
    bg: "bg-lime-50",
    bordure: "border-lime-400",
    chaines: [
      { nom: "Green Radio", initials: "GR", couleur: "bg-lime-500", auditeurs: "6 800", top: true },
      { nom: "Planète FM", initials: "PF", couleur: "bg-green-600", auditeurs: "4 200", top: false },
      { nom: "Éco Vibes", initials: "EV", couleur: "bg-teal-600", auditeurs: "3 100", top: false },
    ],
    emissions: [
      { nom: "Climat Urgent", info: "Lun 18h — Actualités climatiques", live: true },
      { nom: "Nature & Vie", info: "Mer 17h — Biodiversité & faune", live: false },
      { nom: "Zéro Déchet", info: "Sam 10h — Conseils pratiques", live: false },
      { nom: "Énergie Verte", info: "Jeu 19h — Renouvelables & innovations", live: false },
      { nom: "Forêts du Monde", info: "Dimanche 11h — Déforestation & solutions", live: false },
      { nom: "Océan Bleu", info: "Ven 20h — Protection des mers", live: true },
    ],
  },
  {
    id: 4,
    nom: "Éducation",
    emoji: "",
    stats: "7 chaînes · 30 émissions",
    meta: "Sciences, Histoire, Langues, Développement personnel...",
    couleur: "text-blue-600",
    bg: "bg-blue-50",
    bordure: "border-blue-400",
    chaines: [
      { nom: "Radio Savoir", initials: "RS", couleur: "bg-blue-500", auditeurs: "11 200", top: true },
      { nom: "Langue Plus", initials: "LP", couleur: "bg-sky-500", auditeurs: "7 400", top: false },
      { nom: "Science FM", initials: "SF", couleur: "bg-cyan-500", auditeurs: "5 900", top: true },
    ],
    emissions: [
      { nom: "Histoire du Monde", info: "Lun 20h — Grandes civilisations", live: false },
      { nom: "Apprends l'Anglais", info: "Mar & Jeu 17h — Niveau débutant à avancé", live: true },
      { nom: "Science Expliquée", info: "Mer 19h — Physique, chimie, biologie", live: false },
      { nom: "Philo du Soir", info: "Ven 21h — Grands penseurs & débats", live: false },
      { nom: "Maths Faciles", info: "Sam 9h — Exercices & astuces", live: false },
      { nom: "Développement Personnel", info: "Dim 10h — Confiance & motivation", live: true },
    ],
  },
  {
    id: 5,
    nom: "Actualités",
    emoji: "",
    stats: "10 chaînes · 42 émissions",
    meta: "Politique, Économie, International, Société...",
    couleur: "text-red-600",
    bg: "bg-red-50",
    bordure: "border-red-400",
    chaines: [
      { nom: "Info 24/7", initials: "I2", couleur: "bg-red-500", auditeurs: "31 000", top: true },
      { nom: "Éco Radio", initials: "ER", couleur: "bg-orange-500", auditeurs: "14 700", top: true },
      { nom: "Monde FM", initials: "MF", couleur: "bg-rose-500", auditeurs: "19 200", top: false },
    ],
    emissions: [
      { nom: "Journal de 8h", info: "Chaque matin 8h — Revue de presse", live: true },
      { nom: "Débat Politique", info: "Lun & Mer 21h — Invités & analyses", live: false },
      { nom: "Bourse & Marchés", info: "Mar 12h — Actualités économiques", live: true },
      { nom: "Afrique en Direct", info: "Ven 19h — Actualités du continent", live: false },
      { nom: "Société & Vous", info: "Jeu 18h — Sujets de société", live: false },
      { nom: "Flash Info", info: "Toutes les heures — Résumé 5 min", live: true },
    ],
  },
  {
    id: 6,
    nom: "Culture",
    emoji: "",
    stats: "6 chaînes · 28 émissions",
    meta: "Cinéma, Littérature, Art, Théâtre, Gastronomie...",
    couleur: "text-yellow-600",
    bg: "bg-yellow-50",
    bordure: "border-yellow-400",
    chaines: [
      { nom: "Ciné Radio", initials: "CR", couleur: "bg-yellow-500", auditeurs: "8 600", top: true },
      { nom: "Livre FM", initials: "LF", couleur: "bg-amber-500", auditeurs: "5 100", top: false },
      { nom: "Art & Culture", initials: "AC", couleur: "bg-orange-400", auditeurs: "4 700", top: false },
    ],
    emissions: [
      { nom: "Cinéma du Monde", info: "Ven 20h — Critiques & avant-premières", live: false },
      { nom: "Livre du Mois", info: "1er sam du mois 15h — Interviews auteurs", live: false },
      { nom: "Galerie Sonore", info: "Mer 18h — Visites guidées virtuelles", live: true },
      { nom: "Gastronomie FM", info: "Dim 12h — Recettes & chefs étoilés", live: false },
      { nom: "Théâtre en Direct", info: "Jeu 21h — Pièces & mises en scène", live: true },
      { nom: "Mode & Tendances", info: "Mar 17h — Fashion & créateurs", live: false },
    ],
  },
  {
    id: 7,
    nom: "Technologie",
    emoji: "",
    stats: "6 chaînes · 26 émissions",
    meta: "IA, Startups, Cybersécurité, Innovation...",
    couleur: "text-slate-600",
    bg: "bg-slate-50",
    bordure: "border-slate-400",
    chaines: [
      { nom: "Tech Radio", initials: "TR", couleur: "bg-slate-500", auditeurs: "13 400", top: true },
      { nom: "Startup FM", initials: "SF", couleur: "bg-gray-600", auditeurs: "7 800", top: true },
      { nom: "Cyber News", initials: "CN", couleur: "bg-zinc-500", auditeurs: "6 200", top: false },
    ],
    emissions: [
      { nom: "IA & Futur", info: "Lun 20h — Intelligence artificielle", live: true },
      { nom: "Startups Africa", info: "Mer 19h — Entrepreneurs du continent", live: false },
      { nom: "Cybersécurité Now", info: "Jeu 21h — Menaces & protections", live: false },
      { nom: "Code & Dev", info: "Mar 18h — Programmation & astuces", live: true },
      { nom: "Gadgets & Tech", info: "Ven 17h — Tests & nouveautés", live: false },
      { nom: "Web3 & Crypto", info: "Sam 16h — Blockchain & tendances", live: false },
    ],
  },
  {
    id: 8,
    nom: "Religieux",
    emoji: "",
    stats: "4 chaînes · 20 émissions",
    meta: "Christianisme, Islam, Spiritualité, Méditation...",
    couleur: "text-orange-600",
    bg: "bg-orange-50",
    bordure: "border-orange-400",
    chaines: [
      { nom: "Radio Foi", initials: "RF", couleur: "bg-orange-500", auditeurs: "16 300", top: true },
      { nom: "Islam FM", initials: "IF", couleur: "bg-emerald-600", auditeurs: "12 100", top: true },
      { nom: "Méditation+", initials: "M+", couleur: "bg-violet-500", auditeurs: "4 900", top: false },
    ],
    emissions: [
      { nom: "Message du Matin", info: "Chaque jour 6h — Prière & méditation", live: true },
      { nom: "Prêche du Vendredi", info: "Ven 13h — Khoutba en direct", live: true },
      { nom: "Bible & Vie", info: "Dim 9h — Lecture & commentaires", live: false },
      { nom: "Spiritualité Zen", info: "Mer 20h — Pleine conscience", live: false },
      { nom: "Chants Sacrés", info: "Sam 18h — Gospel, Nasheeds, Cantiques", live: false },
      { nom: "Questions de Foi", info: "Jeu 21h — Débats & théologie", live: false },
    ],
  },
];